version: "3.0"

services:
  flask:
    image: duckietown/autolab_control_flask_scripts:daffy-amd64
    container_name: flask
    network_mode: host
    ports:
      - 5050:5050/tcp
    volumes:
      - ./code/autolab:/code/dt-autolab-api/autolab
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/aido_ws/:/tmp/aido_ws/
#      - ~/.ssh/:/external_ssh
      - ~/.ipfs:/root/.ipfs
      - ~/code/duckietown-ttic/TTIC-autolab-fleet-roster:/roster
